services:
  # for development purposes
  dev:
    build: .
    volumes:
      - ./src:/code/src
      - ./data:/data
    environment:
      - KBC_DATADIR=/data

    mem_limit: 256m
  test:
    build: .
    volumes:
      - ./src:/code/src
      - ./data:/data
    environment:
      - KBC_DATADIR=/data
    command:
      - /bin/sh
      - build_n_test.sh
  bash:
    build: .
    volumes:
      - ./src:/code/src
      - ./data:/data
    environment:
      - KBC_DATADIR=/data

    command:
      - /bin/sh
      - build_n_test.sh